# Generated by Django 4.2.1 on 2023-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Post title')),
                ('description', models.TextField(verbose_name='Post text')),
                ('author', models.CharField(max_length=100, verbose_name='Author name')),
                ('post_date', models.DateField(verbose_name='post creation date')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
