# Generated by Django 4.2.1 on 2023-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_alter_post_options_post_owner_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='image/default.jpg', upload_to='image/%Y', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
